openapi: 3.0.0
info:
  title: Просто мир
  description: Документация api запросов для chatbot
  version: 0.0.1

servers:
  - url: http://194.87.147.5:8100/api/v1
    description: url хоста на котором развернут backend

paths:
   /chatbot/products:
       get:
          tags:
            - Товары
          summary: Запрос на получение перечня товаров партнеров
          description: >
            Получение массива товаров по имени и описанию. Поиск по имени имеет больший приоритет
          parameters:
             - name: partnerId
               in: query
               description: >
                массив ID партнеров, по которым будет выполнен поиск продуктов. В случае если значение равно null поиск будет выполнен по всем партнерам
               schema:
                 type: array
             - name: X-GUID-Key
               in: header
               schema:
                 type: string
                 format: uuid
               description: >
                 Ключ для доступа к API из внешних сервисов.
               required: true
          responses:
              '200':
                description: >
                 Поиск товаров выполнен успешно
                content:
                  application/json:
                    schema:
                     type: 'array'
                     items:
                        $ref: '#/components/schemas/Remnants'
              '404':
                $ref: '#/components/responses/NotFound'
              '400':
                $ref: '#/components/responses/BadRequest'
              '401':
                $ref: '#/components/responses/Unauthorized'
              '5XX':
                $ref: '#/components/responses/Unexpected'

   /chatbot/search/products/onstock:
       get:
          tags:
            - Товары
          summary: Запрос на поиск товаров по имени и описанию, которые в наличии
          description: >
            Получение массива товаров по имени и описанию, которые есть в наличии. Поиск по имени имеет больший приоритет
          parameters:
             - name: partnerId
               in: query
               description: >
                Массив ID партнеров, по которым будет выполнен поиск продуктов. В случае если значение равно null поиск будет выполнен по всем партнерам
               schema:
                 type: array
             - name: term
               in: query
               schema:
                type: string
               required: true
               description: Cтроковые символы для поиска товаров
             - name: X-GUID-Key
               in: header
               schema:
                 type: string
                 format: uuid
               description: >
                 Ключ для доступа к API из внешних сервисов.
               required: true
          responses:
              '200':
                description: >
                 Поиск товаров выполнен успешно
                content:
                  application/json:
                    schema:
                     type: 'array'
                     items:
                        $ref: '#/components/schemas/Remnants'
              '404':
                $ref: '#/components/responses/NotFound'
              '400':
                $ref: '#/components/responses/BadRequest'
              '401':
                $ref: '#/components/responses/Unauthorized'
              '5XX':
                $ref: '#/components/responses/Unexpected'

   /chatbot/products/{productId}/photo:
        get:
          tags:
            - Товары
          summary: Запрос на получение фотографии товара
          parameters:
            - name: X-GUID-Key
              in: header
              schema:
                type: string
                format: uuid
              description: >
                Ключ для доступа к API из внешних сервисов.
              required: true
          responses:
           '200':
             description: >
              Фотография товара получена
             content:
               image/png:
                 schema:
                   type: string
                   format: binary
               image/jpeg:
                  schema:
                    type: string
                    format: binary
           '404':
             $ref: '#/components/responses/NotFound'
           '400':
             $ref: '#/components/responses/BadRequest'
           '401':
             $ref: '#/components/responses/Unauthorized'
           '5XX':
             $ref: '#/components/responses/Unexpected'

   /chatbot/remnants/products/{productId}/:
        get:
          tags:
            - Товары
          summary: Запрос на получение остатков товара
          description: >
           Запрос на получение остатков товара партнера по ID продукта
          parameters:
           - name: X-GUID-Key
             in: header
             schema:
               type: string
               format: uuid
             description: >
               Ключ для доступа к API из внешних сервисов.
             required: true
           - name: productId
             in: path
             required: true
             schema:
               type: integer
               format: int64
             description: ID товара
           - name: partnerId
             in: query
             description: >
               Массив ID партнеров, по которым будет выполнен поиск продукта. В случае если значение равно null поиск будет выполнен по всем партнерам
             schema:
               type: array
          responses:
            '200':
              description: >
               Поиск отстатка товара выполнен успешно
              content:
                application/json:
                  schema:
                   type: 'array'
                   items:
                     $ref: '#/components/schemas/Remnants'
            '404':
              $ref: '#/components/responses/NotFound'
            '400':
              $ref: '#/components/responses/BadRequest'
            '401':
              $ref: '#/components/responses/Unauthorized'
            '5XX':
              $ref: '#/components/responses/Unexpected'

components:
  responses:
    NotFound:
      description: Указанный ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Не авторизованный
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unexpected:
      description: Ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Проверьте запрос отправленный серверу
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Customers:
      content:
        application/json:
          schema:
             $ref: '#/components/schemas/Error'
  schemas:
    Items:
      type: object
      description: Модель. Описания товара
      properties:
        id:
          type: integer
        title:
          type: string
        fk_measurement_units_id:
          type: integer
        fk_partner_id:
          type: integer
        article:
          type: integer
        short_title:
          type: string
        barcode:
          type: string
        description:
          type: string
        price_by_unit:
          type: number
          format: double
        photo:
          type: string
        create_at:
          type: string
          format: date
        update_at:
          type: string
          format: date
      required:
        - id
        - title
        - fk_measurement_units_id
        - article
        - short_title
        - barcode
        - description
        - price_by_unit
        - create_at
        - update_at

    Remnants:
      type: object
      description: Модель. Отсатки товаров
      properties:
        id:
          type: integer
        fk_items_id:
          type: integer
        quantity:
          type: integer
        fk_systems_connections_id:
          type: integer
        fk_storages_id:
          type: integer
        fk_partner_id:
          type: integer
        create_at:
          type: string
          format: date
        update_at:
          type: string
          format: date
      required:
        - id
        - fk_items_id
        - quantity
        - fk_storages_types_id
        - fk__systems_connections_id
        - fk_storages_id
        - create_at
        - update_at

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message